### ISSUE TITLE
Feedback 01

### ISSUE THREAD

**Issue by Mikearaya** [MattBaer77/Capstone-1-Baer#1]
Overall the app is performing without major issues. These are some of the things I think would make the app more robust 
- [x] username validation when logging in could be case insensitive since the DB is enforcing uniqueness
- [x] input validation is missing I can enter a text on a field that expects a number (also a bug) because submitting the finish workout will not work if the input is invalid
- [x] back button
- [x] It is not possible to add multiple goals for a single workout using the UI
- [x] user-friendly date display would be great
- [x] pie chart would convey the information better instead of a graph
- [x] Instead of having a separate get_author method in the Workout model, you could use the author property to get the author of the workout. This can be achieved by specifying backref='authored_workouts' in the User.workouts_authored relationship definition.
- [x] You could add indexes on the foreign key columns for faster querying. For instance, in the Goal model, add Index('idx_workout_id', 'workout_id') and Index('idx_exercise_id', 'exercise_id').
- [x] You could consider using a different hashing algorithm for password hashing, such as `Argon2`, which is currently considered more secure than` bcrypt`.
- [x] Use consistent naming conventions: It's important to use consistent naming conventions throughout your code. For example, some of the form classes have names that are in camel case (WorkoutAddForm, PerformanceAddForm), while others have names that are in snake case (UserAddForm, user_edit_form). It's a good practice to stick with one convention throughout the code.
- [x] Use CSRF protection: Flask-WTF provides built-in Cross-Site Request Forgery (CSRF) protection, but it's not being used in the current implementation. CSRF protection is important for preventing malicious attacks, so it's a good idea to use it in your forms.
- [x] The code does not have any error handling in place, so if an error occurs (such as a network error when calling the WGER API), the code will crash. It's good practice to include error handling to handle unexpected scenarios and provide useful error messages. Also Adding retries could improve the resilience of the code.
- [x] It's unclear why the Exercise model is imported since it's not used in this code snippet. If it's not being used, it should be removed to keep the code clean.
- [x] The use of f-strings in the append statement is not necessary since the variables being appended are already strings.

**Comment by MattBaer77** [comment]
- Username validation now case insensitive - considering use of "vanity username" to maintain user's desired casing in UI.
- Input validation issue fixed on forms where feedback was missing.
- Indexes added to models.py Workout.description and User.username
- I have a question about button CSRF tokens. See Route app.py - /goal/id/delete, goals/add.html, and forms.py - GoalDeleteForm - delete button for goals in a workout. For an approach to CSRF protection on delete routes and other POST routes that are wrapping single buttons (no other form fields). Let me know if this is a legitimate approach or hacky.
